/**
 * @module CocoonMain
 * @description
 * Main entry point for Cocoon extension host process.
 * This follows Wind's pattern for bootstrap and service initialization.
 * 
 * Architecture:
 * 1. Service mapping and dependency injection
 * 2. IPC communication with Mountain
 * 3. Extension lifecycle management

































































































































































































export { runCocoon };}  runCocoon();if (require.main === module) {// Export for testing};  NodeRuntime.runMain(main);  // Run the main effect  }    console.log(`[CocoonMain] Added VSCode output directory: ${vsCodeOutputDir}`);    (module as any).paths.unshift(vsCodeOutputDir);  if (vsCodeOutputDir) {  const vsCodeOutputDir = process.env["VSCODE_OUT_DIR"];  // Apply VSCode output directory if available    console.log("[CocoonMain] Starting Cocoon extension host...");const runCocoon = () => { */ * Run Cocoon/**);  Effect.provide(ServiceMappingInstance.composeAppLayer())  handleErrors,const main = bootstrapCocoon.pipe( */ * Main entry point/**// --- Main Execution ---);  })    process.exit(1);    // Attempt graceful shutdown        yield* Effect.logError("Cocoon process terminating due to error");    console.error("[CocoonMain] Fatal error:", error);  Effect.gen(function* () {const handleErrors = Effect.catchAll((error: any) => */ * Error handling and recovery/**  });    console.log("[CocoonMain] IPC handlers registered");    });      process.exit(0);      // Exit process            // TODO: Implement proper deactivation      // Deactivate all extensions            console.log("[CocoonMain] Received shutdown request from Mountain");    yield* ipcService.registerHandler("$shutdown", async () => {    // Handle shutdown requests    });      );        extensionHost.deactivateExtension(extensionId)      return Effect.runPromise(    yield* ipcService.registerHandler("$deactivateExtension", async (extensionId: string) => {    // Handle extension deactivation requests    });      );        extensionHost.activateExtension(extensionId, activationEvent)      return Effect.runPromise(    yield* ipcService.registerHandler("$activateExtension", async (extensionId: string, activationEvent: string) => {    // Handle extension activation requests    console.log("[CocoonMain] Registering IPC handlers...");  Effect.gen(function* () {const registerIPCHandlers = (ipcService: any, extensionHost: any) => */ * Register IPC handlers for Mountain communication/**  });    yield* Effect.never;    // Keep process alive    yield* registerIPCHandlers(ipcService, extensionHost);    // Register IPC handlers    console.log("[CocoonMain] Entering main event loop...");  Effect.gen(function* () {const enterEventLoop = (ipcService: any, extensionHost: any) => */ * Enter main event loop/**  });    console.log(`[CocoonMain] Activated ${startupExtensions.length} startup extensions`);    }      yield* extensionHost.activateExtension(extensionId, "*");    for (const extensionId of startupExtensions) {    const startupExtensions = ["*" as any]; // Placeholder    // TODO: Get extension list from Mountain    console.log("[CocoonMain] Activating startup extensions...");  Effect.gen(function* () {const activateStartupExtensions = (extensionHost: any) => */ * Activate startup extensions/**  );    )      })        return Effect.fail(error);        yield* Effect.logError("Failed to handshake with Mountain");        console.error("[CocoonMain] Handshake failed:", error);      Effect.gen(function* () {    Effect.catchAll((error) =>  }).pipe(    return initData;    console.log("[CocoonMain] Received initialization data from Mountain");    const initData = yield* ipcService.sendRequest("$getInitData", []);    // Wait for initialization data    yield* ipcService.sendNotification("$initialHandshake", []);    // Send initial handshake notification    console.log("[CocoonMain] Performing handshake with Mountain...");  Effect.gen(function* () {const performHandshake = (ipcService: any) => */ * Perform handshake with Mountain/**});  yield* enterEventLoop(ipcService, extensionHost);  // Enter main event loop  console.log("[CocoonMain] Startup extensions activated");  yield* activateStartupExtensions(extensionHost);  // Start extension activation  console.log("[CocoonMain] Extension host initialized");  const extensionHost = yield* ExtensionHostService;  // Initialize extension host  console.log("[CocoonMain] Handshake with Mountain completed");  yield* performHandshake(ipcService);  // Perform handshake with Mountain  console.log("[CocoonMain] Module interceptor installed");  yield* moduleInterceptor.install();  const moduleInterceptor = yield* ModuleInterceptorService;  // Install module interceptor  console.log("[CocoonMain] IPC service initialized");  const ipcService = yield* IPCService;  // Initialize IPC communication  console.log("[CocoonMain] Application layer composed");  const appLayer = ServiceMappingInstance.composeAppLayer();  // Compose application layer  yield* ServiceMappingInstance.validateDependencies();  // Validate service dependencies  console.log("[CocoonMain] Starting Cocoon bootstrap...");const bootstrapCocoon = Effect.gen(function* () { */ * Bootstrap the Cocoon extension host/**// --- Bootstrap Logic ---import { ModuleInterceptorService } from "./ServiceMapping.js";import { IPCService } from "./ServiceMapping.js";import { ExtensionHostService } from "./ServiceMapping.js";import { ServiceMappingInstance } from "./ServiceMapping.js";// Service mappingimport { NodeRuntime } from "@effect/platform-node";import { Effect, Layer } from "effect"; */ * - Add error handling and recovery * - Create proper IPC communication * - Implement actual service implementations * TODOs: * 
