/**
 * @module Codegen/Emit/EmitExtHostSchema
 * @description
 * Cocoon-side schema emitter. Mirrors Wind's `EmitServiceSchema`
 * but lands files under `Cocoon/Source/Effect/Generated/<Decorator>/
 * <Decorator>Upstream.ts` and tags the paired MainThread
 * counterpart so the bridge can wire both ends of the RPC.
 * Idempotent. Re-running on an unchanged record produces
 * byte-identical output.
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "@codeeditorland/wind/Target/Codegen/Type/CodegenProblem.js";
import type {
	InterfaceMemberParameter,
	InterfaceMemberRecord,
} from "@codeeditorland/wind/Target/Codegen/Type/InterfaceMemberRecord.js";

import type { ExtHostDecoratorRecord } from "../../../../Type/Ext/Host/Decorator/Record.js";

const FormatDocComment = (doc: string | null, indent: string): string => {
	if (!doc) return "";

	const Lines = doc.split(/\r?\n/);

	const Body = Lines.map((line) => `${indent} * ${line}`.trimEnd()).join(
		"\n",
	);

	return `${indent}/**\n${Body}\n${indent} */\n`;
};

const FormatParameter = (parameter: InterfaceMemberParameter): string =>
	`${parameter.Name}${parameter.Optional ? "?" : ""}: ${parameter.TypeText}`;

const FormatMember = (member: InterfaceMemberRecord): string => {
	const Doc = FormatDocComment(member.DocComment, "	");

	const ReadonlyPrefix = member.Readonly ? "readonly " : "";

	const OptionalSuffix = member.Optional ? "?" : "";

	if (member.Kind === "Method") {
		const Parameters = member.Parameters.map(FormatParameter).join(", ");

		return `${Doc}	${ReadonlyPrefix}${member.Name}${OptionalSuffix}(${Parameters}): ${member.TypeText};`;
	}

	return `${Doc}	${ReadonlyPrefix}${member.Name}${OptionalSuffix}: ${member.TypeText};`;
};

const FormatMemberRecord = (
	member: InterfaceMemberRecord,

	index: number,

	total: number,
): string => {
	const Parameters = member.Parameters.map(
		(parameter: { Name: string; TypeText: string; Optional: boolean }) =>
			`{ Name: ${JSON.stringify(parameter.Name)}, TypeText: ${JSON.stringify(parameter.TypeText)}, Optional: ${parameter.Optional} }`,
	).join(", ");

	const DocText = member.DocComment
		? JSON.stringify(member.DocComment)
		: "null";

	const Trailing = index === total - 1 ? "" : ",";

	return [
		`	{`,

		`		Kind: "${member.Kind}",`,

		`		Name: ${JSON.stringify(member.Name)},`,

		`		Readonly: ${member.Readonly},`,

		`		Optional: ${member.Optional},`,

		`		TypeText: ${JSON.stringify(member.TypeText)},`,

		`		Parameters: [${Parameters}],`,

		`		DocComment: ${DocText},`,

		`		SourceLine: ${member.SourceLine},`,

		`	}${Trailing}`,
	].join("\n");
};

const FormatOutput = (record: ExtHostDecoratorRecord): string => {
	const Sorted = [...record.Members].sort(
		(a, b) => a.SourceLine - b.SourceLine,
	);

	const InterfaceTypeName = `${record.DecoratorName}Upstream`;

	const InterfaceBody =
		Sorted.length === 0
			? "	// (no members extracted - resolve cross-file)"
			: Sorted.map(FormatMember).join("\n");

	const RecordList =
		Sorted.length === 0
			? ""
			: Sorted.map((member, index) =>
					FormatMemberRecord(member, index, Sorted.length),
				).join("\n");

	const Header = [
		"/**",

		` * Generated by Cocoon/Codegen from`,

		` * ${record.SourcePath}:${record.SourceLine}`,

		` * (decorator tag ${JSON.stringify(record.DecoratorTag)}).`,

		" * DO NOT EDIT BY HAND. Re-run codegen to refresh.",

		" */",

		"",

		'import type { InterfaceMemberRecord } from "@codeeditorland/wind/Target/Codegen/Type/InterfaceMemberRecord.js";',

		"",

		`export const ${record.DecoratorName}Tag = ${JSON.stringify(record.DecoratorTag)} as const;`,

		`export const ${record.DecoratorName}SourcePath = ${JSON.stringify(record.SourcePath)} as const;`,

		`export const ${record.DecoratorName}SourceLine = ${record.SourceLine} as const;`,

		`export const ${record.DecoratorName}MainThreadCounterpart = ${
			record.MainThreadCounterpart
				? JSON.stringify(record.MainThreadCounterpart)
				: "null"
		} as const;`,

		"",

		`export interface ${InterfaceTypeName} {`,

		InterfaceBody,

		"}",

		"",

		`export const ${record.DecoratorName}Members: ReadonlyArray<InterfaceMemberRecord> = [`,

		RecordList,

		"] as const;",

		"",
	];

	return Header.join("\n");
};

export interface EmitExtHostSchemaOptions {
	readonly Record: ExtHostDecoratorRecord;

	readonly OutputRoot: string;
}

export interface EmitExtHostSchemaOutcome {
	readonly OutputPath: string;

	readonly Bytes: number;

	readonly Members: number;
}

export const EmitExtHostSchema = async (
	options: EmitExtHostSchemaOptions,
): Promise<EmitExtHostSchemaOutcome | CodegenProblem> => {
	const Output = FormatOutput(options.Record);

	const OutputPath = join(
		options.OutputRoot,

		"Effect",

		"Generated",

		options.Record.DecoratorName,

		`${options.Record.DecoratorName}Upstream.ts`,
	);

	try {
		await mkdir(dirname(OutputPath), { recursive: true });

		await writeFile(OutputPath, Output, "utf8");

		return {
			OutputPath,

			Bytes: Buffer.byteLength(Output),

			Members: options.Record.Members.length,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",

			path: OutputPath,

			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitExtHostSchema;
